---
title: "Model building"
author: "Kelly Chin"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R libraries
```{r}
library(readxl)
library(performance)
library(survival)
library(survminer)
library(tidyr)
library(gtsummary)
library(coxme)
library(lme4)
library(nlme)
```

# Linear Model
```{r}
Three <- read_excel("../data/raw/Three.xlsx")
Three$CalvingYear <- as.factor(Three$CalvingYear)

mod1 <- lm(Three$DFCFirstHeat~Three$AvgKeto20_atleast10 + Three$MaxKetoDFC20 + factor(Three$ad_Lactation) + Three$PeakDFC + Three$AvgMY20 + Three$CalvingSeason + factor(Three$FarmNo))
summary(mod1)
plot(mod1)

mod1_AvgMY <- lm(Three$DFCFirstHeat~Three$AvgKeto20_atleast10 + factor(Three$ad_Lactation) + Three$PeakDFC +Three$CalvingSeason + factor(Three$FarmNo))
summary(mod1_AvgMY)

anova(mod1, mod1_AvgMY)

mod1.1 <- lm(Three$DFCFirstHeat~Three$AvgKeto20_atleast10 + Three$Lactation + Three$PeakDFC + Three$AvgMY20 + Three$CalvingSeason + factor(Three$FarmNo))
summary(mod1.1)

anova(mod1, mod1.1)


# Log transformation
Three.log <- Three %>%
  mutate(log.DFC_CLA = log(DFC_CLA),
         log.DFCFirstHeat = log(DFCFirstHeat), 
         log.DaysToFirstIns = log(DaysToFirstIns), 
         log.AvgKeto20 = log(AvgKeto20_atleast10), 
         log.AvgKeto60 = log(AvgKeto60_atleast10)) #4327 obs of 71v
         

mod1.log <- lm(Three.log$log.DFCFirstHeat~Three.log$AvgKeto20_atleast20 + Three.log$ad_Lactation + Three.log$PeakDFC + Three.log$AvgMY60 + Three.log$CalvingSeason)
summary(mod1.log)
plot(mod1.log)

mod2.log <- lm(Three.log$log.DFCFirstHeat~Three.log$log.AvgKeto20 + Three.log$ad_Lactation + Three.log$PeakDFC + Three.log$AvgMY60 + Three.log$CalvingSeason)
mod2.log2 <- lm(log.DFCFirstHeat~log.AvgKeto20 + factor(ad_Lactation) + PeakDFC + AvgMY60 + CalvingSeason, data = Three.log)
summary(mod2.log)
summary(mod2.log2)
plot(mod2.log)

anova(mod1.log, mod2.log)
compare_performance(mod1.log, mod2.log, rank = TRUE)
```

# Generalized Linear Model
```{r}
glm.mod1 <- glm(DFCFirstHeat~AvgKeto20_atleast10 + factor(ad_Lactation) + PeakDFC + AvgMY60 + CalvingSeason, family = "gaussian", data = Three)

glm.log1 <- glm(log.DFCFirstHeat~log.AvgKeto20 + factor(ad_Lactation) + PeakDFC + AvgMY60 + CalvingSeason, data = Three.log, family = "gaussian")
summary(glm1.log) # the same as linear model
glm1.log$aic

anova(glm.mod1, glm.log1, test = "Chisq")
```

# Survival regression
```{r}
## Example
#df.surv1 <- survfit(Surv(rDFC, KetoCow)~ad_Lactation, data=Three)
#summary(df.surv1)
#plot(df.surv1, main="Cumulative Survival Function", lty=c(1, 2, 3, 4), xlab="Day after calving (day)", ylab="Probability")
#legend(x=0, y=0.6)
```
```{r}
Three.surv <- Three %>%
  mutate(FirstHeat = ifelse(is.na(Three$DFCFirstHeat), 0, 1)) %>%
  mutate(FirstAI = ifelse(is.na(Three$DaysToFirstIns), 0, 1)) %>%
  mutate(KetoStatus20 = ifelse(Three$AvgKeto20_atleast10 >= 0.08, 1, 0)) %>%
  mutate(KetoQua = ifelse(Three$AvgKeto20_atleast10 >= 0.076, 4, 
                          ifelse(Three$AvgKeto20_atleast10 >= 0.061 & Three$AvgKeto20_atleast10 < 0.076, 3, 
                                 ifelse(Three$AvgKeto20_atleast10 >= 0.055 & Three$AvgKeto20_atleast10 < 0.061, 2, 
                                        ifelse(Three$AvgKeto20_atleast10 < 0.055, 1, NA))))) %>%
  mutate(KetoMaxDay = ifelse(Three$MaxKetoDFC20 >= 17, 4, 
                             ifelse(Three$MaxKetoDFC20 >= 12 & Three$MaxKetoDFC20 < 17, 3,
                                    ifelse(Three$MaxKetoDFC20 >= 8 & Three$MaxKetoDFC20 < 12, 2, 
                                           ifelse(Three$MaxKetoDFC20 <8, 1, NA))))) %>%
  mutate(KetoMaxDay2 = ifelse(Three$MaxKetoDFC20 >= 12, 1, 0))

summary(Three.surv)
Three.surv$KetoStatus20 <- as.character(Three.surv$KetoStatus20)
Three.surv$ad_Lactation <- as.character(Three.surv$ad_Lactation)
Three.surv$KetoQua <- as.character(Three.surv$KetoQua)
```

# Survival curves (DFCFirstHeat)
```{r}
surv.heat <- survfit(Surv(DFCFirstHeat, FirstHeat) ~ 1, data = Three.surv)
plot(surv.heat, main = "Cumulatvie survival time from calving to first heat",
     ylab = "Cumulative survival probability",
     xlab = "Time (days from calving to first heat)")
print(surv.heat)
ggsurvplot(surv.heat, data = Three.surv,
           surv.median.line = "hv",
           xlab = "Time (days from calving to first heat",
           legend.title = "Cumulative survival time to first heat",
           pval = TRUE,
           conf.int = TRUE,
           risk.table = TRUE,
           tables.height = 0.2,
           tables.theme = theme_cleantable(),
           ggtheme = theme_bw())

surv1.heat <- survfit(Surv(DFCFirstHeat, FirstHeat) ~ ad_Lactation, data=Three.surv)
print(surv1.heat)
ggsurvplot(surv1.heat, data=Three.surv,
           surv.median.line = "hv",
           xlab = "Days from Calving to First Heat",
           legend.title = "Parity", 
           legend.labs = c("1", "2", "3", "4+"),
           pval = TRUE, 
           conf.int = TRUE, 
           risk.table = TRUE,
           tables.height = 0.28, 
           tables.theme = theme_cleantable(),
           ggtheme = theme_bw())

# Change font size, style and color
#++++++++++++++++++++++++++++++++++++
if (FALSE) {
# Change font size, style and color at the same time
ggsurvplot(surv1.heat, data = Three.surv,  main = "Survival curve",
   font.main = c(16, "bold", "darkblue"),
   font.x = c(14, "bold.italic", "red"),
   font.y = c(14, "bold.italic", "darkred"),
   font.tickslab = c(12, "plain", "darkgreen"))
}

surv2.heat <- survfit(Surv(DFCFirstHeat, FirstHeat) ~ KetoStatus20, data=Three.surv)
summary(surv2.heat)
print(surv2.heat) #risk table
ggsurvplot(surv2.heat, data=Three.surv,
           surv.median.line = "hv",
           xlab = "Days from Calving to First Heat",
           legend.title = "Ketosis status within 20 DFC", 
           legend.labs = c("Avg. BHB < 0.08", "Avg. BHB ≥ 0.08"),
           pval = TRUE, 
           conf.int = TRUE, 
           risk.table = TRUE,
           tables.height = 0.2, 
           tables.theme = theme_cleantable(),
           ggtheme = theme_bw())

surv3.heat <- survfit(Surv(DFCFirstHeat, FirstHeat) ~ KetoQua, data=Three.surv)
print(surv3.heat)
ggsurvplot(surv3.heat, data=Three.surv,
           surv.median.line = "hv",
           xlab = "Days from Calving to First Heat",
           legend.title = "Avg. BHB within 20 DFC (mmol/L)", 
           legend.labs = c("<0.055", "0.055-0.061", "0.061-0.076", "≥0.076"),
           pval = TRUE, 
           conf.int = TRUE, 
           risk.table = TRUE,
           tables.height = 0.28, 
           tables.theme = theme_cleantable(),
           ggtheme = theme_bw())

surv4.heat <- survfit(Surv(DFCFirstHeat, FirstHeat) ~ KetoMaxDay, data=Three.surv)
print(surv4.heat)
ggsurvplot(surv4.heat, data=Three.surv,
           surv.median.line = "hv",
           xlab = "Days from Calving to First Heat",
           legend.title = "Day when BHB reached maximum within 20 DFC (DFC)", 
           legend.labs = c("< 8 days", "8-12", "12-17", "17-20"),
           pval = TRUE, 
           conf.int = TRUE, 
           risk.table = TRUE,
           tables.height = 0.28, 
           tables.theme = theme_cleantable(),
           ggtheme = theme_bw())

surv5.heat <- survfit(Surv(DFCFirstHeat, FirstHeat) ~ KetoMaxDay2, data=Three.surv)
print(surv5.heat)
ggsurvplot(surv5.heat, data=Three.surv,
           surv.median.line = "hv",
           xlab = "Days from Calving to First Heat",
           legend.title = "Day when BHB reached maximum within 20 DFC (DFC)", 
           legend.labs = c("<12", "12-20"),
           pval = TRUE, 
           conf.int = TRUE, 
           risk.table = TRUE,
           tables.height = 0.2, 
           tables.theme = theme_cleantable(),
           ggtheme = theme_bw())

```

# Cox regression model
```{r}
coxph(Surv(DFCFirstHeat, FirstHeat) ~ KetoStatus20, data = Three.surv)
```

# Cox hazard proportional regression
```{r}
## First Heat
df.cox1.heat <- coxph(Surv(DFCFirstHeat, FirstHeat) ~ ad_Lactation + AvgKeto20_atleast10 + PeakDFC + AvgMY60 + CalvingSeason + factor(FarmNo), data = Three.surv)
summary(df.cox1.heat)

ggsurvplot(survfit(df.cox1.heat), data = Three.surv, color= "#2E9FDF", ggtheme = theme_minimal())

ggsurv <- ggsurvplot(survfit(df.cox1.heat), data = Three.surv, 
                     fun = "cumhaz", conf.int = TRUE, 
                     risk.table = TRUE, risk.table.col = "strata", 
                     ggtheme = theme_bw())
curv_facet <- ggsurv$plot + facet_grid(AvgKeto20_atleast10 ~ PeakDFC + AvgMY60 + CalvingSeason + factor(FarmNo))
curv_facet

## First AI
df.cox1.ai <- coxph(Surv(DaysToFirstIns, FirstAI) ~ AvgKeto20_atleast10 + factor(ad_Lactation) + PeakDFC + AvgMY60 + CalvingSeason + factor(FarmNo), data = Three.surv)
summary(df.cox1.ai)

ggsurvplot(survfit(df.cox1.ai), data = Three.surv, color= "#2E9FDF", ggtheme = theme_minimal())
```
