---
title: "Poisson regression"
author: "Kelly Chin"
date: "4/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R libraries
```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(performance)
library(survival)
library(survminer)
library(gtsummary)
library(coxme)
#library(lme4)
#detach("package:lme4", unload=TRUE)
library(nlme)
library(DHARMa)
library(MASS)
library(arm)
library(foreign)
#install.packages("glmmTMB")
library(glmmTMB)
```

```{r}
Three <- read_excel("../data/raw/Three.xlsx")
#Three$CalvingYear <- as.factor(ifelse(Three$CalvingYear == 2018, 1, 2))
summary(Three)

summary(Three$Last_AI)
sd(Three$Last_AI, na.rm = T)
var(Three$Last_AI, na.rm = T)

# Categorize numbers of AI
#Three <- Three %>%
#  mutate(NumAI = ifelse(Three$Last_AI > 4, 4, 
#                        ifelse(Three$Last_AI <= 4 & Three$Last_AI > 2, 3,
#                               ifelse(Three$Last_AI <= 2 & Three$Last_AI > 1, 2, 
#                                      ifelse(Three$Last_AI == 1, 1, NA)))))

Three.offset <- Three %>%
  mutate(Calving.lastAI = difftime(Last_InsDate, CalvingDate, units = "days"))
Three.offset$Calving.lastAI <- as.numeric(round(Three.offset$Calving.lastAI, 0))
summary(Three.offset$Calving.lastAI)

plot(Three.offset$Calving.lastAI, Three.offset$Last_AI)

boxplot(Three.offset$DaysToFirstIns~Three.offset$FarmNo)
```

# Research Question: what is the assocation of numbers of AI and ketosis?

# AvgKeto20_100
```{r}
p.mod1 <- glm(Last_AI ~ AvgKeto20_atleast10 + ad_Lactation + PeakDFC + AvgMY60 + CalvingSeason + factor(FarmNo), family = poisson(link = "log"), data = Three)
summary(p.mod1)

qp.mod1 <- glm(Last_AI ~ AvgKeto20_atleast10 + ad_Lactation + PeakDFC + AvgMY60 + CalvingSeason + factor(FarmNo), family = quasipoisson(link = "log"), data = Three)
summary(qp.mod1)

coef1 = coef(p.mod1)
coef2 = coef(qp.mod1)
se.coef1 = se.coef(p.mod1)
se.coef2 = se.coef(qp.mod1)
models.both <- cbind(coef1, se.coef1, coef2, se.coef2, exponent = exp(coef1))
models.both

nb.mod1 <- glm.nb(Last_AI ~ AvgKeto20_atleast10 + ad_Lactation + PeakDFC + AvgMY60 + CalvingSeason + factor(FarmNo), data = Three)
summary(nb.mod1)
coef3 = coef(nb.mod1)

#nb.mod2 <- glm.nb(Last_AI ~ AvgKeto20_atleast10 + ad_Lactation + PeakDFC + AvgMY60 + CalvingSeason, 
#                  random = ~ 1|FarmNo,
#                  data = Three)
# doesn't work
```

## lme with random effect
```{r}
mod1.lme <- lme(Last_AI ~ AvgKeto20_100 + MaxKetoDFC20 + factor(ad_Lactation) + PeakDFC + AvgMY20 + CalvingSeason, 
                random = ~ 1|FarmNo, 
                data = Three, 
                na.action = na.exclude,
                method = "REML")
summary(mod1.lme)

mod2.lme <- lme(Last_AI ~ AvgKeto20_100  + factor(ad_Lactation) + PeakDFC + AvgMY60 + CalvingSeason, 
                random = ~ 1|FarmNo, 
                data = Three, 
                na.action = na.exclude,
                method = "REML")
summary(mod2.lme)
```

## glm
```{r}
rm(list=ls(pattern="cox."))
boxplot(Three$Last_AI ~ Three$FarmNo)
plot(Three$AvgKeto20_atleast10, Three$Last_AI)
boxplot(Three$AvgKeto20_atleast10 ~ Three$FarmNo)

poi.mod <- glm(Last_AI ~ 1, data = Three, family = poisson(link = "log"))
summary(poi.mod)

poi.mod1 <- glm(Last_AI ~ AvgKeto20_100, data = Three, family = poisson(link = "log"))
summary(poi.mod1)
```

## Offset - farmsize
```{r}
mod1 <- glm(Last_AI ~ AvgKeto20_100, data = Three, family = poisson(link = "log"))
summary(mod1)

#mod2 <- glm(Last_AI ~ AvgKeto20_100 + offset(log(CowNo)), data = Three, family = poisson(link = "log"))
#(mod2)
## This model doesn't mean anything because the outcome is the 'mean numbers of insemination of an individual cow' and should not be divided to farm size -> shouldn't use farm size in offset! 

mod3 <- glmer(Last_AI ~ AvgKeto20_100 + (1|FarmNo), data = Three, family = poisson(link = "log"))
summary(mod3)
res3 <- simulateResiduals(mod3)
plot(res3)

#mod4 <- glmer(Last_AI ~ AvgKeto20_100 + offset(log(CowNo)) + (1|FarmNo), data = Three, family = poisson(link = "log"))
## This model doesn't mean anything because the outcome is the 'mean numbers of insemination of an individual cow' and should not be divided to farm size -> shouldn't use farm size in offset! 

mod4 <- glmer(Last_AI ~ AvgKeto20_100 + cut(CowNo, c(0, 100, 180, 1000)) + offset(log(Calving.lastAI/30)) + (1|FarmNo), data = Three.offset, family = poisson(link = "log"))
# This model estimates the mean numbers of AI within the estimated observation time (per month), with fix average ketosis and fix farm effect (estimate the effect of farm size)
summary(mod4)
res4 <- simulateResiduals(mod4)
plot(res4)

mod5 <- glmer(Last_AI ~ AvgKeto20_100 + offset(log(Calving.lastAI/30)) + (1|FarmNo), data = Three.offset, family = poisson(link = "log"))
summary(mod5)


summary(mod4)
res4 <- simulateResiduals(mod4)
plot(res4)

boxplot(Three$AvgKeto20_100 ~ Three$Last_AI)
boxplot(Three$Last_AI ~ Three$FarmNo)
boxplot(Three$AvgKeto20_100 ~ Three$FarmNo)

ggplot(data = Three, aes(x = Last_AI, y = AvgKeto20_100)) +
  geom_bar(stat = "identity")
```

## glmmTMB
```{r}
fit1 <- glmmTMB(Last_AI ~ AvgKeto20_100 + cut(CowNo, c(0, 100, 180, 1000)) + offset(log(Calving.lastAI/30)) + (1|FarmNo), data = Three.offset, family = poisson(link = "log"))
summary(fit1)
res.fit1 <- simulateResiduals(fit1)
plot(res.fit1)
```

## Offset - time from calving to last AI
```{r}
mod5 <- glm(Last_AI ~ AvgKeto20_100 + offset(log(Calving.lastAI)), data = Three.offset, family = poisson(link = "log"))
summary(mod5)

mod6 <- glmer(Last_AI ~ AvgKeto20_100 + offset(log(Calving.lastAI)) + (1|FarmNo), data = Three.offset, family = poisson(link = "log"))
summary(mod6)

summary(mod6)
res6 <- simulateResiduals(mod6)
plot(res6)

anova(mod5, mod6)
drop1(mod6)
```

## glmer
```{r}
mod1.poisson <- glmer(Last_AI ~ AvgKeto20_atleast10 + MaxKetoDFC20 + factor(ad_Lactation) + PeakDFC + AvgMY20 + CalvingSeason + (1 | FarmNo), 
                      data = Three, family = poisson(link = "log"))
summary(mod1.poisson)

mod0.poisson <- glmer(Last_AI ~ 1 + (1 | FarmNo), data = Three, family = poisson(link = "log"))
summary(mod2.poisson)
```

## glmer 
```{r}
poi.avgketo20 <- glmer(Last_AI~ AvgKeto20_atleast10 + (1 | FarmNo), 
                      data = Three, family = poisson(link = "log"))
summary(poi.avgketo20)
anova(poi.mod, poi.avgketo20, test = "Chisq")
drop1(poi.avgketo20)

poi.avgketo20.1 <- glmer(Last_AI~ AvgKeto20_atleast10 + (FarmNo), 
                      data = Three, family = poisson(link = "log"))
summary(poi.avgketo20.1)

poi.avgketo20.cate <- glmer(Last_AI~ cut(AvgKeto20_atleast10, c(0, 0.04, 0.07, 0.1, 0.5)) + (1 | FarmNo), 
                      data = Three, family = poisson(link = "log"))
summary(poi.avgketo20.cate)

poi.avgketo20.100 <- glmer(Last_AI~ AvgKeto20_100 + (1 | FarmNo), 
                      data = Three, family = poisson(link = "log"))
summary(poi.avgketo20.100)

```

# KetoDur20
```{r}
rm(list=ls(pattern="mod"))
summary(Three$KetoDur20)
#Days of ketosis
Three$KetoDur20 <- as.factor(Three$KetoDur20)
ggplot(data=Three, aes(x=factor(KetoDur20)))+
  geom_bar(stat="count", fill="lightblue") +
  stat_count(geom="text", size=3, aes(label=..count..)) +
  ggtitle("Distribution of KetoDur20") +
  theme_classic() +
  xlab("days of milk BHB over 0.08 mmol/L within 20 DFC") +
  ylab("#cows")

Three$KetoDur20 <- as.numeric(Three$KetoDur20)
summary(Three$Last_AI)
boxplot(Three$Last_AI ~ Three$FarmNo)
boxplot(Three$KetoDur20 ~ Three$Last_AI)
boxplot(Three$KetoDur20 ~ Three$FarmNo)
```

## glm
```{r}
poi.mod <- glm(Last_AI ~ 1, data = Three, family = poisson(link = "log"))
summary(poi.mod)

poi.mod1 <- glm(Last_AI ~ KetoDur20, data = Three, family = poisson(link = "log"))
summary(poi.mod1)

p.mod <- glm(Last_AI ~ KetoDur20 + factor(ad_Lactation) + PeakDFC + AvgMY60 + CalvingSeason + factor(FarmNo), family = poisson(link = "log"), data = Three)
summary(p.mod)
#plot(p.mod)

p.mod_no_Lact <- glm(Last_AI ~ KetoDur20 + PeakDFC + AvgMY60 + CalvingSeason + factor(FarmNo), family = poisson(link = "log"), data = Three) 
summary(p.mod_no_Lact)
#plot(p.mod_no_Lact)
```

## Offset - farmsize
```{r}
mod1 <- glm(Last_AI ~ KetoDur20, data = Three, family = poisson(link = "log"))
summary(mod1)

#mod2 <- glm(Last_AI ~ KetoDur20 + offset(log(CowNo)), data = Three, family = poisson(link = "log"))
#summary(mod2)
## This model doesn't mean anything because the outcome is the 'mean numbers of insemination of an individual cow' and should not be divided to farm size

mod3 <- glmer(Last_AI ~ KetoDur20 + (1|FarmNo), data = Three, family = poisson(link = "log"))
summary(mod3)

#mod4 <- glmer(Last_AI ~ KetoDur20 + offset(log(CowNo)) + (1|FarmNo), data = Three, family = poisson(link = "log"))
## This model doesn't mean anything because the outcome is the 'mean numbers of insemination of an individual cow' and should not be divided to farm size -> shouldn't use farm size in offset! 

anova(mod1, mod2, test = "Chisq")
anova(mod1, mod3, test = "Chisq")
plot(mod3)
anova(mod3, mod4, test="Chisq")

res3 <- simulateResiduals(mod3)
plot(res3)
```

## Offset - time from calving to last AI
```{r}
mod5 <- glm(Last_AI ~ KetoDur20 + offset(log(Calving.lastAI)), data = Three.offset, family = poisson(link = "log"))
summary(mod5)

mod6 <- glmer(Last_AI ~ KetoDur20 + offset(log(Calving.lastAI)) + (1|FarmNo), data = Three.offset, family = poisson(link = "log"))
summary(mod6)

anova(mod5, mod6)
drop1(mod6)
```

# Extra AI
```{r}
extra <- Three.offset %>%
  filter(Last_AI >= 1)
mean(extra$Last_AI)
var(extra$Last_AI)
table(extra$Last_AI)

mod.extra <- glmer(Last_AI ~ AvgKeto20_100 + cut(CowNo, c(0, 100, 180, 1000)) + offset(log(Calving.lastAI/30)) + (1|FarmNo), data = extra, family = poisson(link = "log"))
summary(mod.extra)
res.extra <- simulateResiduals(mod.extra)
plot(res.extra)

mod.extra2 <- glmer(Last_AI ~ AvgKeto20_100)


```
